//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListBoxInfo", Namespace="http://schemas.datacontract.org/2004/07/TwitterFriendsSearcher.Runner")]
    [System.SerializableAttribute()]
    public partial class ListBoxInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwitterFriendsSearcherUiProvider.ITwitterFriendsSearcherUiInfoProvider")]
    public interface ITwitterFriendsSearcherUiInfoProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetButtonCenterByName", ReplyAction="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetButtonCenterByNameRes" +
            "ponse")]
        Test.TwitterFriendsSearcher.Shared.ControlCenter GetButtonCenterByName(string buttonName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetTextBoxCenterByName", ReplyAction="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetTextBoxCenterByNameRe" +
            "sponse")]
        Test.TwitterFriendsSearcher.Shared.ControlCenter GetTextBoxCenterByName(string textBoxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetListBoxInfo", ReplyAction="http://tempuri.org/ITwitterFriendsSearcherUiInfoProvider/GetListBoxInfoResponse")]
        Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider.ListBoxInfo GetListBoxInfo(string listBoxInfoName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwitterFriendsSearcherUiInfoProviderChannel : Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider.ITwitterFriendsSearcherUiInfoProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwitterFriendsSearcherUiInfoProviderClient : System.ServiceModel.ClientBase<Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider.ITwitterFriendsSearcherUiInfoProvider>, Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider.ITwitterFriendsSearcherUiInfoProvider {
        
        public TwitterFriendsSearcherUiInfoProviderClient() {
        }
        
        public TwitterFriendsSearcherUiInfoProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwitterFriendsSearcherUiInfoProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterFriendsSearcherUiInfoProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterFriendsSearcherUiInfoProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Test.TwitterFriendsSearcher.Shared.ControlCenter GetButtonCenterByName(string buttonName) {
            return base.Channel.GetButtonCenterByName(buttonName);
        }
        
        public Test.TwitterFriendsSearcher.Shared.ControlCenter GetTextBoxCenterByName(string textBoxName) {
            return base.Channel.GetTextBoxCenterByName(textBoxName);
        }
        
        public Test.TwitterFriendsSearcher.TwitterFriendsSearcherUiProvider.ListBoxInfo GetListBoxInfo(string listBoxInfoName) {
            return base.Channel.GetListBoxInfo(listBoxInfoName);
        }
    }
}
